### ISSUE TITLE
session support? ssl cookies?

### ISSUE THREAD

**Issue by NextStepGuru** [alfhen/vue-cookie#12]
Would it be possible to add session cookies and ssl cookie support?

**Comment by alfhen** [comment]
@NextStepGuru Since the purpose of this plugin is not to contain any code for actually setting cookies but just providing a wrapper for the awesome Tiny cookie library, I do not believe it would make sense to implement these features in this plugin. But I believe that the latest version of tiny cookie contains a secure option, meaning you should be able to do:
``` javascript 

Vue.cookie.set('someKey', 'someValue', { secure: true });

```
Regarding the session cookies if it is something you need you should make a issue on: https://github.com/Alex1990/tiny-cookie/issues
