### ISSUE TITLE
<script> tag doesn't work

### ISSUE THREAD

**Issue by felipecaldas** [alfhen/vue-cookie#18]
Hi there,

Just installed this module and in my client HTML I have :

<script src="/node_modules/vue-cookie/build/vue-cookie.js'"></script>

I am getting a 404 from NodeJs:
GET http://localhost:3000/node_modules/vue-cookie/build/vue-cookie.js 
GET /node_modules/vue-cookie/build/vue-cookie.js 404 8.950 ms - 2634

is it not possible to read straight from the node_module?

Thank you

**Comment by felipecaldas** [comment]
And, I did check the node_modules folder. vue-cookie is there :)

**Comment by paladosss** [comment]
I have this problem too! Please tell what to do!?

**Comment by paladosss** [comment]
I think this does not work because I have poorly defined the connections. 

// Require dependencies 
var Vue = require('vue');
var VueCookie = require('vue-cookie');

Where should I do this?

**Comment by felipecaldas** [comment]
That would be in your server side, @paladosss 
I am trying to do that in the client side.

**Comment by Dried09** [comment]
You may use something like webpack, if so - when you build your app or start dev server, open page with script tag in browser described file path does not exists, because build of your application has no folder node_modules, all dependencies will be bundled, but, probably, not dependencies imported via script tag.

To fix this problem you can use lib path from cdn, i.e.:

`<script src="https://cdn.jsdelivr.net/npm/vue-cookies@1.5.6/vue-cookies.min.js"></script>`

or create (or locate if it already exists) public folder in root of your project, place vue-cookie.min.js here and link it like:

`<script src="./vue-cookies.min.js"></script>`
